# Generated by Django 4.1.7 on 2023-03-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testdb", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
