# Generated by Django 4.1.7 on 2023-04-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_story_profile_like_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="date_posted",
        ),
        migrations.AddField(
            model_name="story",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="story_tags",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
