# Generated by Django 4.1.7 on 2023-04-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_profile_followers_remove_profile_stories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="uuid",
        ),
    ]
