# Generated by Django 4.1.7 on 2023-04-15 17:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_auto_20230415_1729"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followings",
        ),
        migrations.AddField(
            model_name="story",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_stories", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="story_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255, null=True),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
