# Generated by Django 4.1.7 on 2023-04-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_remove_user_followings_story_likes_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
