# Generated by Django 4.1.7 on 2023-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="followings",
            field=models.IntegerField(null=True),
        ),
    ]
