# Generated by Django 4.1.7 on 2023-04-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=10, max_digits=19)),
                ("longitude", models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.RemoveField(
            model_name="story",
            name="location",
        ),
        migrations.AddField(
            model_name="story",
            name="locations",
            field=models.ManyToManyField(blank=True, to="user.location"),
        ),
    ]
