# Generated by Django 4.1.7 on 2023-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_location_remove_story_location_story_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("latitude", "longitude")},
        ),
    ]
