# Generated by Django 4.1.7 on 2023-04-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_location_latitude_alter_location_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="end_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="season",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="start_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
