# Generated by Django 4.1.7 on 2023-04-20 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_story_end_date_story_end_year_story_season_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
