# Generated by Django 4.1.7 on 2023-04-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_story_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together=set(),
        ),
    ]
